=== petrol95/grokking-algorithms/xml/students/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
        attributeFormDefault="unqualified">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student"
                         type="Student"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Student">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="telephone" type="xs:positiveInteger" />
            <xs:element name="address" type="Address" />
        </xs:sequence>
        <xs:attribute name="login" type="Login" use="required" />
        <xs:attribute name="faculty" use="optional" default="mmf">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="mmf"></xs:enumeration>
                    <xs:enumeration value="geo"></xs:enumeration>
                    <xs:enumeration value="ksis"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="Login">
        <xs:restriction base="xs:ID">
            <xs:pattern value="([a-zA-Z])[a-zA-Z0-9]{7,19}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Address">
        <xs:sequence>
            <xs:element name="country" type="xs:string" />
            <xs:element name="city" type="xs:string" />
            <xs:element name="street" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== petrol95/grokking-algorithms/xml/students/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE students SYSTEM "students.dtd">-->
    <students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/"
        xsi:schemaLocation="http://www.example.com/student ../students.xsd">
            <student login="MitarAlex7" faculty="mmf">
                <name>Mitar Alex</name>
                <telephone>2456474</telephone>
                <address>
                    <country>Belarus</country>
                    <city>Minsk</city>
                    <street>Kalinovsky 45</street>
                </address>
            </student>
            <student login="Pashkin5" faculty="mmf">
                <name>Pashkin Alex</name>
                <telephone>3453789</telephone>
                <address>
                    <country>Belarus</country>
                    <city>Brest</city>
                    <street>Knorina 56</street>
                </address>
            </student>
    </students>
